import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :galicia_local, GaliciaLocalWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :galicia_local, GaliciaLocalWeb.Endpoint,
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  exclude: [
    # paths: ["/health"],
    hosts: ["localhost", "127.0.0.1"]
  ]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Enrichment and translation schedulers DISABLED in production.
# These heavy jobs (Claude CLI, web scraping, research) are run locally
# and synced to prod via the content export/import pipeline.
# See CONTENT_WORKFLOW.md for the local workflow.
# config :galicia_local, enrich_scheduler_cron: "*/5 * * * *"
# config :galicia_local, translate_all_scheduler_cron: "*/10 * * * *"

# Disable all heavy Oban queues in production.
# Only keep default for lightweight background tasks (e.g. emails).
config :galicia_local, Oban,
  queues: [
    default: 5
  ]

# Store discovery crawl data on persistent volume (survives deploys)
config :galicia_local, discovery_data_dir: "/data/claude/discovery"

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
