import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :galicia_local, GaliciaLocalWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :galicia_local, GaliciaLocalWeb.Endpoint,
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  exclude: [
    # paths: ["/health"],
    hosts: ["localhost", "127.0.0.1"]
  ]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Enable enrichment and translation schedulers in production only
# In dev, we use the content export/import pipeline with Claude Code instead
config :galicia_local, enrich_scheduler_cron: "*/5 * * * *"
config :galicia_local, translate_scheduler_cron: "*/15 * * * *"

# CLI enrichment (uses claude --print via Max plan, no API cost)
# Jobs check ENABLE_CLI_ENRICHMENT env var at runtime before doing work
config :galicia_local, enrich_cli_scheduler_cron: "*/5 * * * *"
config :galicia_local, translate_all_scheduler_cron: "*/10 * * * *"

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
