defmodule GaliciaLocal.Repo.Migrations.AddDiscoveryCrawls do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:discovery_crawls, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :crawl_id, :text, null: false
      add :status, :text, null: false, default: "crawling"
      add :seed_urls, {:array, :text}, default: []
      add :max_pages, :bigint, default: 200
      add :pages_crawled, :bigint, default: 0
      add :businesses_created, :bigint, default: 0
      add :businesses_skipped, :bigint, default: 0
      add :businesses_failed, :bigint, default: 0
      add :error, :text
      add :started_at, :utc_datetime
      add :crawl_finished_at, :utc_datetime
      add :processing_started_at, :utc_datetime
      add :completed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :region_id,
          references(:regions,
            column: :id,
            name: "discovery_crawls_region_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :city_id,
          references(:cities,
            column: :id,
            name: "discovery_crawls_city_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:discovery_crawls, [:region_id, :crawl_id],
             name: "discovery_crawls_unique_crawl_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:discovery_crawls, [:region_id, :crawl_id],
                     name: "discovery_crawls_unique_crawl_id_index"
                   )

    drop constraint(:discovery_crawls, "discovery_crawls_region_id_fkey")

    drop constraint(:discovery_crawls, "discovery_crawls_city_id_fkey")

    drop table(:discovery_crawls)
  end
end
