defmodule GaliciaLocal.Repo.Migrations.AddBoundsToScrapeJobs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:scrape_jobs) do
      add :bounds_south, :decimal
      add :bounds_west, :decimal
      add :bounds_north, :decimal
      add :bounds_east, :decimal
    end
  end

  def down do
    alter table(:scrape_jobs) do
      remove :bounds_east
      remove :bounds_north
      remove :bounds_west
      remove :bounds_south
    end
  end
end
