defmodule GaliciaLocal.Repo.Migrations.AddLanguagesTaught do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:businesses) do
      add :languages_taught, {:array, :text}, default: []
    end
  end

  def down do
    alter table(:businesses) do
      remove :languages_taught
    end
  end
end
