defmodule GaliciaLocal.Repo.Migrations.CreateFavorites do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:favorites, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "favorites_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :business_id,
          references(:businesses,
            column: :id,
            name: "favorites_business_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:favorites, [:user_id, :business_id],
             name: "favorites_unique_user_business_index"
           )
  end

  def down do
    drop_if_exists unique_index(:favorites, [:user_id, :business_id],
                     name: "favorites_unique_user_business_index"
                   )

    drop constraint(:favorites, "favorites_user_id_fkey")

    drop constraint(:favorites, "favorites_business_id_fkey")

    drop table(:favorites)
  end
end
