defmodule GaliciaLocal.Repo.Migrations.AddCategoryFitFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  # Increase lock timeout for large businesses table on production
  @disable_ddl_transaction true
  @disable_migration_lock true

  def up do
    execute "SET lock_timeout TO '10s'"

    alter table(:businesses) do
      add_if_not_exists :category_fit_score, :decimal
      add_if_not_exists :suggested_category_slug, :text
    end
  end

  def down do
    alter table(:businesses) do
      remove :suggested_category_slug
      remove :category_fit_score
    end
  end
end
