defmodule GaliciaLocal.Repo.Migrations.AddEnrichmentHintsToCategoryTranslations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:category_translations) do
      add :enrichment_hints, :text
    end
  end

  def down do
    alter table(:category_translations) do
      remove :enrichment_hints
    end
  end
end
