defmodule GaliciaLocal.Repo.Migrations.AddBusinessClaims do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:businesses) do
      add :claimed_at, :utc_datetime

      add :owner_id,
          references(:users,
            column: :id,
            name: "businesses_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:business_claims, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "pending"
      add :message, :text
      add :admin_notes, :text
      add :reviewed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "business_claims_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :business_id,
          references(:businesses,
            column: :id,
            name: "business_claims_business_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:business_claims, [:user_id, :business_id],
             name: "business_claims_unique_user_business_index"
           )
  end

  def down do
    drop_if_exists unique_index(:business_claims, [:user_id, :business_id],
                     name: "business_claims_unique_user_business_index"
                   )

    drop constraint(:business_claims, "business_claims_user_id_fkey")

    drop constraint(:business_claims, "business_claims_business_id_fkey")

    drop table(:business_claims)

    drop constraint(:businesses, "businesses_owner_id_fkey")

    alter table(:businesses) do
      remove :owner_id
      remove :claimed_at
    end
  end
end
