defmodule GaliciaLocal.Repo.Migrations.AddRegionTaglineAndHero do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:regions) do
      add :tagline, :text
      add :hero_image_url, :text
    end
  end

  def down do
    alter table(:regions) do
      remove :hero_image_url
      remove :tagline
    end
  end
end
