defmodule GaliciaLocal.Repo.Migrations.AddUserProfileFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :display_name, :text
      add :bio, :text
      add :origin_country, :text
      add :avatar_url, :text

      add :city_id,
          references(:cities,
            column: :id,
            name: "users_city_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:users, "users_city_id_fkey")

    alter table(:users) do
      remove :city_id
      remove :avatar_url
      remove :origin_country
      remove :bio
      remove :display_name
    end
  end
end
