defmodule GaliciaLocal.Repo.Migrations.AddRegionIdToPageViews do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @galicia_id "74ca7186-ecf4-47e7-856d-f553ce7dbd35"

  def up do
    # Step 1: Add column as nullable first
    alter table(:page_views) do
      add :region_id, :uuid, null: true
    end

    # Step 2: Backfill existing data
    # Business page views - get region from businesses table
    execute """
    UPDATE page_views SET region_id = b.region_id
    FROM businesses b
    WHERE page_views.page_type = 'business' AND page_views.resource_id = b.id
    """

    # City page views - get region from cities table
    execute """
    UPDATE page_views SET region_id = c.region_id
    FROM cities c
    WHERE page_views.page_type = 'city' AND page_views.resource_id = c.id
    """

    # Category page views and any remaining - default to Galicia
    execute """
    UPDATE page_views SET region_id = '#{@galicia_id}'
    WHERE region_id IS NULL
    """

    # Step 3: Make column NOT NULL
    alter table(:page_views) do
      modify :region_id, :uuid, null: false
    end

    # Step 4: Update unique index
    drop_if_exists unique_index(:page_views, [:page_type, :resource_id, :date],
                     name: "page_views_unique_page_day_index"
                   )

    create unique_index(:page_views, [:page_type, :resource_id, :date, :region_id],
             name: "page_views_unique_page_day_index"
           )
  end

  def down do
    drop_if_exists unique_index(:page_views, [:page_type, :resource_id, :date, :region_id],
                     name: "page_views_unique_page_day_index"
                   )

    create unique_index(:page_views, [:page_type, :resource_id, :date],
             name: "page_views_unique_page_day_index"
           )

    alter table(:page_views) do
      remove :region_id
    end
  end
end
