defmodule GaliciaLocal.Repo.Migrations.AddCommunityReviews do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:reviews, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :rating, :bigint, null: false
      add :body, :text
      add :visited, :boolean, default: false
      add :speaks_english_confirmed, :boolean

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "reviews_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :business_id,
          references(:businesses,
            column: :id,
            name: "reviews_business_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:reviews, "reviews_user_id_fkey")

    drop constraint(:reviews, "reviews_business_id_fkey")

    drop table(:reviews)
  end
end
