defmodule GaliciaLocal.Repo.Migrations.AddCategorySearchConfig do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:categories) do
      add :search_translation, :text
      add :search_queries, {:array, :text}, default: []
      add :enrichment_hints, :text
    end
  end

  def down do
    alter table(:categories) do
      remove :enrichment_hints
      remove :search_queries
      remove :search_translation
    end
  end
end
