defmodule GaliciaLocal.Repo.Migrations.CreateDirectoryResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:scrape_jobs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :source, :text, null: false
      add :query, :text
      add :status, :text, null: false, default: "pending"
      add :businesses_found, :bigint, default: 0
      add :businesses_created, :bigint, default: 0
      add :error_message, :text
      add :started_at, :utc_datetime
      add :completed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :city_id, :uuid
      add :category_id, :uuid
    end

    create table(:cities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:scrape_jobs) do
      modify :city_id,
             references(:cities,
               column: :id,
               name: "scrape_jobs_city_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:cities) do
      add :name, :text, null: false
      add :slug, :text, null: false
      add :province, :text, null: false
      add :description, :text
      add :description_es, :text
      add :latitude, :decimal
      add :longitude, :decimal
      add :population, :bigint
      add :featured, :boolean, default: false
      add :image_url, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:cities, [:slug], name: "cities_unique_slug_index")

    create table(:categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:scrape_jobs) do
      modify :category_id,
             references(:categories,
               column: :id,
               name: "scrape_jobs_category_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:categories) do
      add :name, :text, null: false
      add :name_es, :text
      add :slug, :text, null: false
      add :description, :text
      add :icon, :text
      add :priority, :bigint, null: false, default: 4

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :parent_id,
          references(:categories,
            column: :id,
            name: "categories_parent_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:categories, [:slug], name: "categories_unique_slug_index")

    create table(:businesses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false
      add :description, :text
      add :description_es, :text
      add :summary, :text
      add :address, :text
      add :phone, :text
      add :email, :text
      add :website, :text
      add :google_maps_url, :text
      add :latitude, :decimal
      add :longitude, :decimal
      add :languages_spoken, {:array, :text}, default: []
      add :speaks_english, :boolean
      add :speaks_english_confidence, :decimal
      add :rating, :decimal
      add :review_count, :bigint, default: 0
      add :price_level, :bigint
      add :opening_hours, :map
      add :highlights, {:array, :text}, default: []
      add :warnings, {:array, :text}, default: []
      add :status, :text, default: "pending"
      add :source, :text
      add :raw_data, :map
      add :quality_score, :decimal
      add :last_enriched_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :city_id,
          references(:cities,
            column: :id,
            name: "businesses_city_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :category_id,
          references(:categories,
            column: :id,
            name: "businesses_category_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:businesses, [:slug, :city_id],
             name: "businesses_unique_slug_per_city_index"
           )
  end

  def down do
    drop_if_exists unique_index(:businesses, [:slug, :city_id],
                     name: "businesses_unique_slug_per_city_index"
                   )

    drop constraint(:businesses, "businesses_city_id_fkey")

    drop constraint(:businesses, "businesses_category_id_fkey")

    drop table(:businesses)

    drop_if_exists unique_index(:categories, [:slug], name: "categories_unique_slug_index")

    drop constraint(:categories, "categories_parent_id_fkey")

    alter table(:categories) do
      remove :parent_id
      remove :updated_at
      remove :inserted_at
      remove :priority
      remove :icon
      remove :description
      remove :slug
      remove :name_es
      remove :name
    end

    drop constraint(:scrape_jobs, "scrape_jobs_category_id_fkey")

    alter table(:scrape_jobs) do
      modify :category_id, :uuid
    end

    drop table(:categories)

    drop_if_exists unique_index(:cities, [:slug], name: "cities_unique_slug_index")

    alter table(:cities) do
      remove :updated_at
      remove :inserted_at
      remove :image_url
      remove :featured
      remove :population
      remove :longitude
      remove :latitude
      remove :description_es
      remove :description
      remove :province
      remove :slug
      remove :name
    end

    drop constraint(:scrape_jobs, "scrape_jobs_city_id_fkey")

    alter table(:scrape_jobs) do
      modify :city_id, :uuid
    end

    drop table(:cities)

    drop table(:scrape_jobs)
  end
end
