defmodule GaliciaLocal.Repo.Migrations.CreatePageViews do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:page_views, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :page_type, :text, null: false
      add :resource_id, :uuid, null: false
      add :date, :date, null: false
      add :view_count, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:page_views, [:page_type, :resource_id, :date],
             name: "page_views_unique_page_day_index"
           )
  end

  def down do
    drop_if_exists unique_index(:page_views, [:page_type, :resource_id, :date],
                     name: "page_views_unique_page_day_index"
                   )

    drop table(:page_views)
  end
end
