defmodule GaliciaLocal.Repo.Migrations.CreateCategoryTranslations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:category_translations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :locale, :text, null: false
      add :name, :text
      add :search_translation, :text
      add :search_queries, {:array, :text}, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :category_id,
          references(:categories,
            column: :id,
            name: "category_translations_category_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:category_translations, [:category_id, :locale],
             name: "category_translations_unique_category_locale_index"
           )
  end

  def down do
    drop_if_exists unique_index(:category_translations, [:category_id, :locale],
                     name: "category_translations_unique_category_locale_index"
                   )

    drop constraint(:category_translations, "category_translations_category_id_fkey")

    drop table(:category_translations)
  end
end
