defmodule GaliciaLocal.Repo.Migrations.AddSpanishContentFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:categories) do
      add :description_es, :text
    end

    alter table(:businesses) do
      add :summary_es, :text
      add :highlights_es, {:array, :text}, default: []
      add :warnings_es, {:array, :text}, default: []
      add :integration_tips_es, {:array, :text}, default: []
      add :cultural_notes_es, {:array, :text}, default: []
    end
  end

  def down do
    alter table(:businesses) do
      remove :cultural_notes_es
      remove :integration_tips_es
      remove :warnings_es
      remove :highlights_es
      remove :summary_es
    end

    alter table(:categories) do
      remove :description_es
    end
  end
end
