defmodule GaliciaLocal.Repo.Migrations.AddRegionsMultitenancy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Step 1: Create regions table first
    create table(:regions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false
      add :country_code, :text, null: false
      add :default_locale, :text, default: "en"
      add :supported_locales, {:array, :text}, default: fragment("ARRAY['en']::text[]")
      add :timezone, :text, default: "UTC"
      add :active, :boolean, default: true
      add :settings, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:regions, [:slug], name: "regions_unique_slug_index")

    # Step 2: Insert Galicia region
    execute """
    INSERT INTO regions (id, name, slug, country_code, default_locale, supported_locales, timezone, active, settings, inserted_at, updated_at)
    VALUES (
      gen_random_uuid(),
      'Galicia',
      'galicia',
      'ES',
      'en',
      ARRAY['en', 'es']::text[],
      'Europe/Madrid',
      true,
      '{}',
      NOW(),
      NOW()
    )
    """

    # Step 3: Update foreign key constraints
    drop constraint(:users, "users_city_id_fkey")

    alter table(:users) do
      modify :city_id,
             references(:cities,
               column: :id,
               name: "users_city_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:reviews, "reviews_business_id_fkey")

    alter table(:reviews) do
      modify :business_id,
             references(:businesses,
               column: :id,
               name: "reviews_business_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:favorites, "favorites_business_id_fkey")

    alter table(:favorites) do
      modify :business_id,
             references(:businesses,
               column: :id,
               name: "favorites_business_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:business_claims, "business_claims_business_id_fkey")

    alter table(:business_claims) do
      modify :business_id,
             references(:businesses,
               column: :id,
               name: "business_claims_business_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    # Step 4: Add region_id to cities (nullable first)
    alter table(:cities) do
      add :region_id, :uuid
    end

    # Step 5: Migrate existing cities to Galicia region
    execute """
    UPDATE cities SET region_id = (SELECT id FROM regions WHERE slug = 'galicia')
    """

    # Step 6: Add foreign key constraint and make non-nullable
    alter table(:cities) do
      modify :region_id,
             references(:regions,
               column: :id,
               name: "cities_region_id_fkey",
               type: :uuid,
               prefix: "public"
             ),
             null: false
    end

    drop_if_exists unique_index(:cities, [:slug], name: "cities_unique_slug_index")
    create unique_index(:cities, [:region_id, :slug], name: "cities_unique_slug_per_region_index")

    # Step 7: Add region_id to businesses (nullable first)
    drop constraint(:businesses, "businesses_city_id_fkey")

    alter table(:businesses) do
      add :region_id, :uuid
    end

    # Step 8: Migrate existing businesses to Galicia region
    execute """
    UPDATE businesses SET region_id = (SELECT id FROM regions WHERE slug = 'galicia')
    """

    # Step 9: Add foreign key constraint and make non-nullable
    alter table(:businesses) do
      modify :region_id,
             references(:regions,
               column: :id,
               name: "businesses_region_id_fkey",
               type: :uuid,
               prefix: "public"
             ),
             null: false

      modify :city_id,
             references(:cities,
               column: :id,
               name: "businesses_city_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists unique_index(:businesses, [:slug, :city_id],
                     name: "businesses_unique_slug_per_city_index"
                   )

    create unique_index(:businesses, [:region_id, :slug, :city_id],
             name: "businesses_unique_slug_per_city_index"
           )

    # Step 10: Add region_id to scrape_jobs (nullable first)
    drop constraint(:scrape_jobs, "scrape_jobs_city_id_fkey")

    alter table(:scrape_jobs) do
      add :region_id, :uuid
    end

    # Step 11: Migrate existing scrape_jobs to Galicia region
    execute """
    UPDATE scrape_jobs SET region_id = (SELECT id FROM regions WHERE slug = 'galicia')
    """

    # Step 12: Add foreign key constraint and make non-nullable
    alter table(:scrape_jobs) do
      modify :region_id,
             references(:regions,
               column: :id,
               name: "scrape_jobs_region_id_fkey",
               type: :uuid,
               prefix: "public"
             ),
             null: false

      modify :city_id,
             references(:cities,
               column: :id,
               name: "scrape_jobs_city_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    drop constraint(:business_claims, "business_claims_business_id_fkey")

    alter table(:business_claims) do
      modify :business_id,
             references(:businesses,
               column: :id,
               name: "business_claims_business_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists unique_index(:businesses, [:region_id, :slug, :city_id],
                     name: "businesses_unique_slug_per_city_index"
                   )

    drop constraint(:businesses, "businesses_city_id_fkey")

    alter table(:businesses) do
      modify :city_id,
             references(:cities,
               column: :id,
               name: "businesses_city_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:businesses, [:slug, :city_id],
             name: "businesses_unique_slug_per_city_index"
           )

    drop constraint(:businesses, "businesses_region_id_fkey")

    alter table(:businesses) do
      remove :region_id
    end

    drop_if_exists unique_index(:cities, [:region_id, :slug],
                     name: "cities_unique_slug_per_region_index"
                   )

    create unique_index(:cities, [:slug], name: "cities_unique_slug_index")

    drop constraint(:cities, "cities_region_id_fkey")

    alter table(:cities) do
      remove :region_id
    end

    drop constraint(:favorites, "favorites_business_id_fkey")

    alter table(:favorites) do
      modify :business_id,
             references(:businesses,
               column: :id,
               name: "favorites_business_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists unique_index(:regions, [:slug], name: "regions_unique_slug_index")

    alter table(:regions) do
      remove :updated_at
      remove :inserted_at
      remove :settings
      remove :active
      remove :timezone
      remove :supported_locales
      remove :default_locale
      remove :country_code
      remove :slug
      remove :name
    end

    drop constraint(:scrape_jobs, "scrape_jobs_region_id_fkey")

    drop constraint(:scrape_jobs, "scrape_jobs_city_id_fkey")

    alter table(:scrape_jobs) do
      modify :city_id,
             references(:cities,
               column: :id,
               name: "scrape_jobs_city_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :region_id, :uuid
    end

    drop table(:regions)

    drop constraint(:reviews, "reviews_business_id_fkey")

    alter table(:reviews) do
      modify :business_id,
             references(:businesses,
               column: :id,
               name: "reviews_business_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:scrape_jobs) do
      remove :region_id
    end

    drop constraint(:users, "users_city_id_fkey")

    alter table(:users) do
      modify :city_id,
             references(:cities,
               column: :id,
               name: "users_city_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
