defmodule GaliciaLocal.Repo.Migrations.AddCategoryFitFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @disable_ddl_transaction true
  @disable_migration_lock true

  def up do
    # Set statement_timeout to 0 (no limit) and lock_timeout to 30s
    # in a single statement block to ensure they apply to the same connection
    execute "SET statement_timeout = 0"
    execute "SET lock_timeout = '30s'"
    execute "ALTER TABLE businesses ADD COLUMN IF NOT EXISTS category_fit_score decimal"
    execute "ALTER TABLE businesses ADD COLUMN IF NOT EXISTS suggested_category_slug text"
  end

  def down do
    alter table(:businesses) do
      remove :suggested_category_slug
      remove :category_fit_score
    end
  end
end
