defmodule GaliciaLocal.Repo.Migrations.AddCategoryFitFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:businesses) do
      add :category_fit_score, :decimal
      add :suggested_category_slug, :text
    end
  end

  def down do
    alter table(:businesses) do
      remove :suggested_category_slug
      remove :category_fit_score
    end
  end
end
