defmodule GaliciaLocal.Repo.Migrations.AddExpatInsightsToBusinesses do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:businesses) do
      add :expat_friendly_score, :decimal
      add :expat_tips, {:array, :text}, default: []
      add :service_specialties, {:array, :text}, default: []
      add :sentiment_summary, :text
      add :review_insights, :map
    end
  end

  def down do
    alter table(:businesses) do
      remove :review_insights
      remove :sentiment_summary
      remove :service_specialties
      remove :expat_tips
      remove :expat_friendly_score
    end
  end
end
