defmodule GaliciaLocal.Repo.Migrations.RemoveLegacyEsFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cities) do
      remove_if_exists :description_nl, :text
      remove_if_exists :description_es, :text
    end

    alter table(:categories) do
      remove_if_exists :description_es, :text
      remove_if_exists :name_es, :text
    end

    alter table(:businesses) do
      remove_if_exists :cultural_notes_es, {:array, :text}
      remove_if_exists :integration_tips_es, {:array, :text}
      remove_if_exists :warnings_es, {:array, :text}
      remove_if_exists :highlights_es, {:array, :text}
      remove_if_exists :summary_es, :text
      remove_if_exists :description_es, :text
    end
  end

  def down do
    alter table(:businesses) do
      add :description_es, :text
      add :summary_es, :text
      add :highlights_es, {:array, :text}, default: []
      add :warnings_es, {:array, :text}, default: []
      add :integration_tips_es, {:array, :text}, default: []
      add :cultural_notes_es, {:array, :text}, default: []
    end

    alter table(:categories) do
      add :name_es, :text
      add :description_es, :text
    end

    alter table(:cities) do
      add :description_es, :text
      add :description_nl, :text
    end
  end
end
