defmodule GaliciaLocal.Repo.Migrations.AddSuggestions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:suggestions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :business_name, :text, null: false
      add :address, :text
      add :website, :text
      add :phone, :text
      add :reason, :text
      add :status, :text, default: "pending"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "suggestions_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :city_id,
          references(:cities,
            column: :id,
            name: "suggestions_city_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :category_id,
          references(:categories,
            column: :id,
            name: "suggestions_category_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:suggestions, "suggestions_user_id_fkey")

    drop constraint(:suggestions, "suggestions_city_id_fkey")

    drop constraint(:suggestions, "suggestions_category_id_fkey")

    drop table(:suggestions)
  end
end
