defmodule GaliciaLocal.Repo.Migrations.UpdateSuggestionsCityText do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:suggestions) do
      remove :city_id
      modify :category_id, :uuid, null: true
      add :city_name, :text, null: false, default: ""
    end
  end

  def down do
    alter table(:suggestions) do
      remove :city_name
      modify :category_id, :uuid, null: false

      add :city_id,
          references(:cities,
            column: :id,
            name: "suggestions_city_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end
end
