defmodule GaliciaLocal.Repo.Migrations.AddContentSourceToBusinessTranslations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:business_translations) do
      add :content_source, :text, default: "ai_generated"
      add :source_locale, :text, default: "en"
    end
  end

  def down do
    alter table(:business_translations) do
      remove :source_locale
      remove :content_source
    end
  end
end
