defmodule GaliciaLocal.Repo.Migrations.AddIntegrationFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:businesses) do
      add :newcomer_friendly_score, :decimal
      add :local_gem_score, :decimal
      add :integration_tips, {:array, :text}, default: []
      add :cultural_notes, {:array, :text}, default: []
    end
  end

  def down do
    alter table(:businesses) do
      remove :cultural_notes
      remove :integration_tips
      remove :local_gem_score
      remove :newcomer_friendly_score
    end
  end
end
