defmodule GaliciaLocal.Repo.Migrations.AddDescriptionNlToCities do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cities) do
      add :description_nl, :text
    end
  end

  def down do
    alter table(:cities) do
      remove :description_nl
    end
  end
end
